python train_graph_classification.py \
--dataset collab \
--dim_hidden 50 \
--wi_scaling 0.0016 \
--wh_scaling 0.006 \
--n_bit 4 \
--lambdas 1e-3 \
--leaky 0.2 \
--n_iter 4 \
--simulation True \
--noise 0.02 